import React from "react";
import './terms.css'
import {  Link, useLocation } from "react-router-dom";
import { useEffect } from "react";
const Terms = () => {
    const location = useLocation();
    useEffect(() => {
        if (!location.hash) {
            window.scrollTo(0, 0);
        }
    }, [location]);
    return(
        <div className="terms-outer">
            <div className="terms-inner">
                <h1>Terms and Conditions</h1>
                <div className="terms-inner-text">
                    <p>
                    This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
                    <br/>
This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of www.Shopeefashion.com (“Website”).
<br/>
Welcome to [Shopee FASHION] (“” Company or “Site” or “Application”). This Site is owned and operated by Shopee Fashion Limited (“Shopee Fashion”). Shopee Fashion provides an online platform (”Site”) for connecting Users and it does not own any Products or discharge services listed on its Site.
<br/>
USE OF THIS SITE<br/>
Shopee Fashion Limited is a company incorporated under the provisions of the Companies Act, 2013 with its registered office at 104, Vasan Udyog Bhavan, Sun Mill Compound, S.B. Marg, Tulsi Pipe Road, Lower Parel, Mumbai 400 013. You may be accessing our Site from a computer or mobile phone device (through an iOS or Android application, for example) and these Terms of Use govern your use of our Site and your conduct, regardless of the means of access. Shopee Fashion through the Site intends to provide its users a premium curated collection of designer wear to help the affluent fashion-conscious woman evolve her unique style. We aim to create an online experience that is just as indulgent as the process of buying a fashion item in store. The site will be focused on offering a curated assortment, convenience and customer service to help meet the needs of the demanding premium / luxury fashion buyer.
<br/>
The Site is only to be used for your personal non-commercial use and information. Your use of the services and features of the Site shall be governed by these Terms and Conditions (hereinafter "Terms of Use") along with the Privacy Policy, Shipping Policy and Cancellation, Refund and Return Policy (together "Policies") as modified and amended from time to time.
<br/>
For the purpose of these Terms of Use, wherever the context so requires "You" or "User" shall mean any natural or legal person who has agreed to access the Website. By mere accessing or using the Site, you are acknowledging, without limitation or qualification, to be bound by these Terms of Use and the Polices, whether you have read the same or not. ACCESSING, BROWSING OR OTHERWISE USING THE SITE INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS IN THIS AGREEMENT, SO PLEASE READ THIS AGREEMENT CAREFULLY BEFORE PROCEEDING. If you do not agree to any of the terms enumerated in the Terms of Use or the Policies, please do not use the Site.
<br/>
You are responsible to ensure that your access to this Site and material available on or through it are legal in each jurisdiction, in or through which you access or view the site or such material.
<br/>
Shopee Fashion reserves the right to change the particulars contained in the Terms of Use or the Policies from time to time and at any time, without notice to its users and in its sole discretion. If Shopee Fashion decides to change the Terms of Use or Policies, Shopee Fashion will post the new version of the Terms of Use or the Policies on the Site and update the date specified above. Any change or modification to the Terms of Use and the Policies will be effective immediately from the date of such upload of the Terms of Use and Policies on the Site. Your continued use of the Site following the modifications to the Terms of Use and Policies constitutes your acceptance of the modified Terms of Use and Policies whether or not you have read them. For this reason, you should frequently review these Terms of Use, our Guidelines and Rules and any other applicable policies, including their dates, to understand the terms and conditions that apply to your use of the Site.
<br/>
PRIVACY POLICY<br/>
Shopee Fashion may use your Personal Information such as name, e-mail, postal addresses, phone number(s), IP addresses, product interest information and in certain circumstances, your opinions and individual preferences, etc;, (collectively "Personal Information") collected:
<br/>
send you or your friends, relatives or associates, products that you have ordered;
process gift card transaction;
help us learn more about your shopping preferences; or
conduct marketing and performance research to assist us in measuring our customer services, benchmarking our performance and to help us improve your shopping experiences and product offerings.
to send communication related to order updates and offers through e-mail, SMS and social media channels.
You may always choose not to receive promotional materials or marketing information.
<br/>
PLATFORM FOR TRANSACTION & COMMUNICATION
The Site is a platform that Users utilize to meet and interact with one another for their transactions and is anonline platform. Shopee Fashion is not and cannot be a party to or control in any manner any transaction between the Site's Users.
<br/>
Through this online platform, Shopee Fashion only aims to be provide the platform through which buyers and sellers interact and all commercial/contractual terms are offered by and agreed to between Buyers and Sellers independently. These include without limitation the price, shipping costs, payment methods, payment terms, period and mode of delivery, warranties, after sales services, replacement/returns and refunds, related to products and services. Shopee Fashion does not and will not have any control or does not determine or advise or in any way involve itself in the offering or acceptance of such commercial/contractual terms between the Buyers and Sellers. All discounts, offers (including exchange offers) are by the Seller/Brand and not by Shopee Fashion.
<br/>
Placement of order by a Buyer with Seller on the Website is an offer to buy the product(s) in the order by the Buyer to the Seller and it shall not be construed as Seller's acceptance of Buyer's offer to buy the product(s) ordered. The Seller retains the right to cancel any such order placed by the Buyer, at its sole discretion and the Buyer shall be intimated of the same by way of an email/SMS. Any transaction price paid by Buyer in case of such cancellation by Seller, shall be refunded to the Buyer. Further, the Seller may cancel an order wherein the quantities exceed the typical individual consumption. This applies both to the number of products ordered within a single order and the placing of several orders for the same product where the individual orders comprise a quantity that exceeds the typical individual consumption. What comprises a typical individual's consumption quantity limit shall be based on various factors and at the sole discretion of the Seller and may vary from individual to individual.
<br/>
Shopee Fashion is not responsible for any non-performance or breach of any contract entered into between the Buyers and Sellers. It does not and cannot guarantee that any transaction entered into between the Buyers and Sellers will be concluded by such Users and it shall not intervene in any dispute/disagreement between the Users whether through mediation or through any other means to resolve the dispute/disagreement between the Users.
<br/>
Shopee Fashion is not assuming liability and shall not be held liable in any manner whatsoever on account of any monetary loss or other damage suffered by the Customer for delay or failure of delivery, interruption, or corruption of any data or other information transmitted in connection with use or operation of the Platform, . It shall not have any obligations or liabilities in respect of any contract entered into by the Users and it shall not be responsible for unsatisfactory or delayed performance of services or damages or delays as a result of Products that are out of stock, unavailable or back ordered.
<br/>
PRIVACY PRACTICES
We understand the importance of safeguarding your personal information and we have formulated a Privacy Policy, to ensure that your personal information is sufficiently protected. Apart from these Terms of Use, the Privacy Policy shall also govern your visit and use of the Site. Your continued use of the Site implies that you have read and accepted the Privacy Policy and agree to be bound by its terms and conditions. You consent to the use of personal information by Shopee Fashion in accordance with the terms of and purposes set forth in the Privacy Policy, the same may be subject to amendment from time to time at the sole discretion of Shopee Fashion without any notice.
<br/>
YOUR ACCOUNT
This Site is directed to be used by adults only. We assume that any minor, if at all, accessing our Site is under the supervision of their guardians. Shopee Fashion or its associates do not knowingly collect information from minors. You will be responsible for maintaining confidentiality of your account, password, and restricting access to your computer, and you hereby accept responsibility for all activities that occur under your account and password. You acknowledge that the information you provide, in any manner whatsoever, are not confidential or proprietary and does not infringe any rights of a third party.
<br/>
If you are accessing, browsing and using the Site on someone else’s behalf; you represent that you have the authority to bind that person to all the terms and conditions herein. In the event that the person refuses to be bound as the principal to the Terms of Use, you agree to accept liability for any harm caused by any wrongful use of the Site resulting from such access or use of the Site.

If you know or have reasons to believe that the security of your account has been breached, you should contact us immediately at the 'Contact Information' provided below. If we have found a breach or suspected breach of the security of your account, we may require you to change your password, or suspend your account without any liability to Shopee Fashion.
<br/>
We reserve the right to refuse service and/or terminate accounts without prior notice if these Terms of Use and/or Policies are violated or if we decide, in our sole discretion, that it would be in Shopee Fashion’s best interests to do so. You are solely responsible for all content that you upload, post, email or otherwise transmit via the Site. The information provided to us shall be maintained by us in accordance with our Privacy Policy.

PRODUCT & SERVICES INFORMATION
Shopee Fashion attempts to be as accurate as possible in the description of the product on the Site. However, Shopee Fashion does not warrant that the product description, colour, information or other content of the Site is accurate, complete, reliable, current or error-free. The Site may contain typographical errors or inaccuracies and may not be complete or current. The product pictures are indicative and may not match the actual product.
<br/>
Shopee Fashion does not make any representation or warranty as to specifics, such as quality, value, saleability, quantity, completeness, accuracy, legal title etc. of the products or services proposed to be sold or offered to be sold or purchased on the Site. Shopee Fashion does not implicitly or explicitly support or endorse the sale or purchase of any products or services on the Site and it shall not be liable for any actions arising out of any errors, omissions, negligence or any other actions, whether on behalf of itself or third parties.
<br/>
Shopee Fashion reserves the right to correct, change or update information, errors, inaccuracies or omissions at any time (including after an order has been submitted) without prior notice. Please note that such errors, inaccuracies or omissions may also relate to pricing and availability.
<br/>
PRODUCT USE & SERVICES<br/>
The products and services available on the Site, and the samples, if any, that Shopee Fashion may provide you, are for your personal and/or professional use only. The products or services, or samples thereof, which you may receive from us, shall not be sold or resold for any commercial reasons.
<br/>
Shopee Fashion is in no manner responsible for any manufactural defects. Service provider and manufacturer of the product or service shall be solely responsible for such defects and consumer complaints. You should carefully read the individual terms and conditions in relation to the products.
<br/>
RECOMMENDATION OF PRODUCTS & SERVICES<br/>
Any recommendation made to you in the Site during the course of your use of the Site is purely for informational purposes and for your convenience and does not amount to endorsement of the product or services by Shopee Fashion or any of its associates in any manner.
<br/>
PRICING & PAYMENT INFORMATION<br/>
Shopee Fashion strives to provide accurate product and pricing information, however errors may occur. Shopee Fashion cannot confirm the price of the product until you make the order. Without limiting the generality of Clause 9 (Cancellations, Refunds and Returns) below, if a product / service is listed at an incorrect price or with incorrect information due to any technical error, Shopee Fashion shall have the right, at its sole discretion, to refuse or cancel any orders placed for that product/ service, unless the product has already been delivered or the service has already been availed by you. In the event that an item is wrongly priced, Shopee Fashion may, at its discretion, either contact you for instructions or cancel your order and notify you of such cancellation. Unless the product ordered by you has been delivered and the services are availed, your offer will not be deemed accepted and Shopee Fashion will have the right to modify the price of the product/ service and contact you for further instructions using the e-mail address provided by you during the time of registration or placing of order, or cancel the order and notify you of such cancellation. In the event that Shopee Fashion accepts your order the same shall be debited to your credit card account, debit card account or any mode through which the payment was made and duly notified to you by email that the payment has been processed. The payment may be processed prior to Shopee Fashion’s dispatch of the product that you have ordered. If we have to cancel the order after we have processed the payment, the said amount will be reversed to your credit / debit card account.
<br/>
PRICES AND AVAILABILITY OF THE PRODUCTS AND SERVICES PROVIDED OR OFFERED ON THE SITE ARE SUBJECT TO CHANGE WITHOUT PRIOR NOTICE AND AT THE SOLE DISCRETION OF Shopee FASHION. Shopee Fashion may revise and cease to make available any product/ services at any time. In the event, Shopee Fashion is unable to deliver the product to you on time or at all, you will be notified by an e-mail and your order will be automatically cancelled due to unavailability of the product or at your instructions due to failure to deliver the product on the expected time of delivery by our delivery partners. Shopee Fashion shall not be liable to pay for any damages in such an event owing to cancellation of the order or delay in delivery.

CUSTOMS & IMPORT DUTIES INFORMATION FOR INTERNATIONAL ORDERS
You may be subject to import duties that are levied once the package reaches your country. Additional charges for customs clearance must be borne by You; Shopee Fashion has no control over these charges and cannot predict what they may be. Customs policies vary widely from country to country, you should contact your local customs office for further information. Additionally, when ordering from Shopee Fashion, you are considered the importer on record and must comply with all laws and regulations of the country in which you are receiving the merchandise.

CHAT/CALL FUNCTIONALITY
The Chat/Call Functionality has been provided to help you with any and all Site related queries. Any use of this service shall be subject to the following conditions:
<br/>
Shopee Fashion may suspend the chat/call service at any time without notice.
Shopee Fashion or its executives are not responsible for any delay caused in attending to or replying to the queries via chat/call.
Communication through chat/call may be stored by Shopee Fashion for future reference, and the user of such service will not have the right to access such information at any future date.
While 'chatting/calling' you may not communicate any objectionable information i.e. unlawful, threatening, abusive, defamatory, obscene information.
The chat/call room shall not be used to sell any products, to give suggestion on business opportunity or any other form of solicitation.
You may proceed further and chat/call with our online customer care executive only if you agree to the above terms and conditions.
You authorize Shopee Fashion, its group companies and business associates to call, SMS, chat and email you in connection with your order and order updates
USER CONTENT
The information, photo, image, chat communication, text, software, data, music, sound, graphics, messages, videos or other materials transmitted, uploaded, posted, emailed or otherwise made available to us ("User Content"), are entirely your responsibility and we will not be held responsible, in any manner whatsoever, in connection to the User Content. You agree to not encourage or assist or engage others as well as yourself in transmitting, hosting, displaying, uploading, modifying, publishing transmitting, updating or sharing any information that:
<br/>
belongs to another person and to which the user does not have any right to;
is grossly harmful, harassing, blasphemous defamatory, obscene, pornographic, paedophilic, libellous, invasive of another's privacy, hateful, or racially, ethnically objectionable, disparaging, relating or encouraging money laundering or gambling, or otherwise unlawful in any manner whatever;
harm minors in any way;
infringes any patent, trademark, copyright or other proprietary rights;
violates any law for the time being in force;
deceives or misleads the addressee about the origin of such messages or communicates any information which is grossly offensive or menacing in nature;
impersonate another person;
contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer resource;
threatens the unity, integrity, defence, security or sovereignty of India, friendly relations with foreign states, or public order or causes incitement to the commission of any cognizable offence or prevents investigation of any offence or is insulting any other nation.
Shopee Fashion shall in no way be held responsible for examining or evaluating User Content, nor does it assume any responsibility or liability for the User Content. Shopee Fashion does not endorse or control the User Content transmitted or posted on the Site by you and therefore, accuracy, integrity or quality of User Content is not guaranteed by Shopee Fashion. You understand that by using the Site, you may be exposed to User Content that is offensive, indecent or objectionable to you. Under no circumstances will Shopee Fashion be liable in any way for any User Content, including without limitation, for any errors or omissions in any User Content, or for any loss or damage of any kind incurred by you as a result of the use of any User Content transmitted, uploaded, posted, e-mailed or otherwise made available via the Site. You hereby waive all rights to any claims against Shopee Fashion for any alleged or actual infringements of any proprietary rights, rights of privacy and publicity, moral rights, and rights of attribution in connection with User Content
<br/>
You hereby acknowledge that Shopee Fashion has the right (but not the obligation) in its sole discretion to refuse to post or remove any User Content and further reserves the right to change, condense, or delete any User Content. Without limiting the generality of the foregoing or any other provision of these Terms and Conditions, Shopee Fashion has the right to remove any User Content that violates these Terms and Conditions or is otherwise objectionable and further reserves the right to refuse service and/or terminate accounts without prior notice for any users who violate these Terms and Conditions or infringe the rights of others.
<br/>
If you wish to delete your User Content on our Site or in connection with our mobile applications, please contact us by email at support@Shopeefashion.com and request you to include the following personal information in your deletion request: first name, last name, user name/screen name (if applicable), email address associated with our Site and/or mobile applications, your reason for deleting the posting, and date(s) of posting(s) you wish to delete (if you have it). We may not be able to process your deletion request if you are unable to provide such information to us. Please allow up to 30 business days to process your deletion request.
<br/>
Intellectual Property Rights<br/>
The "Shopee Fashion" name and logo and all related product and service names, design marks and slogans are the trademarks, logos or service marks (hereinafter referred to as "Marks") of Shopee Fashion. All other Marks provided on the Site are the property of their respective companies. No trademark or service mark license is granted in connection with the materials contained on this Site. Access to this Site does not authorize anyone to use any Marks in any manner. Marks displayed on this Site, whether registered or unregistered, of Shopee Fashion or others, are the intellectual property of their respective owners, and Shopee Fashion shall not be held liable in any manner whatsoever for any unlawful, unauthorized use of the Marks.
<br/>
Shopee Fashion and its suppliers and licensors expressly reserve all the intellectual property rights in all text, programs, products, processes, technology, content, software and other materials, which appear on this Site, including its looks and feel. The compilation (meaning the collection, arrangement and assembly) of the content on the Site is the exclusive property of Shopee Fashion and are protected by the Indian copyright laws and International treaties. Consequently, the materials on this Site shall not be copied, reproduced, duplicated, republished, downloaded, posted, transmitted, distributed or modified in whole or in part or in any other form whatsoever, except for your personal, non-commercial use only. No right, title or interest in any downloaded materials or software is transferred to you as a result of any such downloading or copying, reproducing, duplicating, republishing, posting, transmitting, distributing or modifying.
<br/>
All materials, including images, text, illustrations, designs, icons, photographs, programs, music clips, downloads, video clips and written and other materials that are part of this Site (collectively, the "Contents") are intended solely for personal, non-commercial use. You shall not download or copy the Contents and other downloadable materials displayed on the Site for your personal use. We also grant you a limited, revocable, non-transferable, and non-exclusive license to create a hyperlink to the home page of the Site for personal, non-commercial use only. The Contents and software on this Site are to be used only as a shopping resource. Any other use, including the reproduction, modification, distribution, transmission, re- publication, display, or performance, of the Contents on this Site is strictly prohibited. Unless Shopee Fashion explicitly provides to the contrary, all Contents are copyrighted, trademarked, trade dressed and/or other intellectual property owned, controlled or licensed by Shopee Fashion, any of its affiliates or by third parties who have licensed their materials to Shopee Fashion and are protected by Indian copyright laws and international treaties.
<br/>
LIMITED LICENSE<br/>
Shopee Fashion grants you limited, non-exclusive, non-transferable, non- sublicensable license to access, and make personal and non-commercial use of the Site. All rights not expressly granted to you in these Terms of Use, are reserved and retained by the Site and its affiliates.
<br/>
Shopee Fashion reserves the right, at any time, without notice, and at its sole discretion, to terminate your license to use the Site and to block and prevent your future access the Site.
<br/>
Web Browser Cookies<br/>
Cookies are small pieces of information that are stored by a web server on a web browser so it can be later read back from that browser. No personal information about you is gathered or stored in the cookies by the Website and, as a result, none can be passed on to any third parties. We use cookies and other technologies such as pixel tags and clear gifs to store certain types of information each time you visit any page on our Website/Application. Cookies enable the Website/Application to recognize the information you have consented to give to the Website/Application and help us determine what portions of this Website/Application are most appropriate for your personal needs. Most cookies are ‘session cookies’ meaning that they are automatically deleted from your device at the end of a session.
<br/>
User may choose to set their web browser to refuse cookies. If you haven't changed your computer's settings, most likely your browser already accepts cookies. If you choose to decline cookies, you may not be able to fully experience all features of the website. You can also delete your browser cookies or disable them entirely. But this may significantly impact your experience with our website and may make parts of our website non-functional or inaccessible.
<br/>
Third Party Services & Websites<br/>
Website/Application does not control the content or links that appear on the third- party websites and is not responsible for the practices employed by these websites linked to or from our Website/Application, even if users may find content on our site that links to the sites and services of our partners, suppliers, advertisers, sponsors, licensors and other third parties. In addition, these sites or services, including their content and links, may be constantly changing. These sites and services may have their own privacy policies and customer service policies. Browsing and interaction on any other website, including websites which have a link to our Website/Application, is subject to that website’s own terms and conditions.
<br/>
You, on your risk and volition entirely, are advised to deal with the services of our partners, suppliers, advertisers, sponsors, licensors and other third parties if you intend to. By allowing such advertisements, Shopee Fashion does not recommend or market or warranty the advertisers, the quality, commitment, deliverables, fitness for consumption, reasonability of their products/services or the advertisers’ commitment to protect your Personal Information.

Representations & Warranties
This Site is provided to you "AS IS". We make no representations regarding the use of or the result of the use/depiction of the Contents on the Site in terms of their correctness, accuracy, reliability, or otherwise. Shopee Fashion shall not be liable for any loss suffered in any manner by the user as a result of depending directly or indirectly on the depiction of the Content on this Site.

You acknowledge that this Site is provided only on the basis set out in the Terms of Use. Your uninterrupted access or use of this Site on this basis may be prevented by certain factors outside our reasonable control including, without limitation, the unavailability, inoperability or interruption of the internet or other telecommunications services or as a result of any maintenance or other service work carried out on this Site.

Shopee Fashion shall have the right, at any time, to change or discontinue any aspect or feature of the Site, including, but not limited to, content, hours of availability and equipment needed for access or use. Further, the Site may discontinue disseminating any portion of information or category of information. Shopee Fashion does not accept any responsibility and will not be liable for any loss or damage whatsoever arising out of or in connection with any ability/inability to access or to use the Site.
<br/>
Shopee Fashion makes no representation and takes no responsibility for the accuracy, completeness, appropriateness or usefulness of the Information.
<br/>
In keeping with Shopee Fashion’s objective of providing \its users with general information about the Garments, Accessories, etc., Shopee Fashion engages experts having knowledge of in their respective fields ("Experts") to respond to queries posted by users. Any information provided by the Experts, either over the Site, through e-mails, chat rooms or on social networking sites, including the Site's Facebook page (collectively referred to as "Expert's Opinion") is based on the Experts personal opinion.
<br/>
For any general information posted on the Site, users must not infer or assume that such information necessarily applies to them.
<br/>
Disclaimer of Warranty and Limitation of Liability<br/>
THE SITE IS PRESENTED "AS IS." NEITHER WE NOR OUR HOLDING, SUBSIDIARIES, AFFILIATES, PARTNERS, OR LICENSORS MAKE ANY REPRESENTATIONS OR WARRANTIES OF ANY KIND WHATSOEVER, EXPRESS OR IMPLIED, IN CONNECTION WITH THESE TERMS AND CONDITIONS OR THE SITE OR ANY OF THE CONTENT, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-INFRINGEMENT OR FITNESS FOR A PARTICULAR PURPOSE, EXCEPT TO THE EXTENT SUCH REPRESENTATIONS AND WARRANTIES ARE NOT LEGALLY EXCLUDABLE.
<br/>
YOU AGREE THAT, TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, NEITHER WE NOR OUR HOLDING, SUBSIDIARIES, AFFILIATES, PARTNERS, OR LICENSORS WILL BE RESPONSIBLE OR LIABLE (WHETHER IN CONTRACT, TORT (INCLUDING NEGLIGENCE) OR OTHERWISE) UNDER ANY CIRCUMSTANCES FOR ANY (a) INTERRUPTION OF BUSINESS; (b) ACCESS DELAYS OR ACCESS INTERRUPTIONS TO THE SITE; (c) DATA NON-DELIVERY, LOSS, THEFT, MISDELIVERY, CORRUPTION, DESTRUCTION OR OTHER MODIFICATION; (d) LOSS OR DAMAGES OF ANY SORT INCURRED AS A RESULT OF DEALINGS WITH OR THE PRESENCE OF OFF-WEBSITE LINKS ON THE SITE; (e) VIRUSES, SYSTEM FAILURES OR MALFUNCTIONS WHICH MAY OCCUR IN CONNECTION WITH YOUR USE OF THE SITE, INCLUDING DURING HYPERLINK TO OR FROM THIRD PARTY WEBSITES; (f) ANY INACCURACIES OR OMISSIONS IN CONTENT; OR (g) EVENTS BEYOND THE REASONABLE CONTROL OF Shopee FASHION. WE MAKE NO REPRESENTATIONS OR WARRANTIES THAT DEFECTS OR ERRORS WILL BE CORRECTED.
<br/>
FURTHER, TO THE FULLEST EXTENT PERMITTED BY LAW, NEITHER WE NOR OUR SUBSIDIARIES, AFFILIATES, PARTNERS, OR LICENSORS WILL BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE, INCIDENTAL, OR CONSEQUENTIAL DAMAGES OF ANY KIND (INCLUDING LOST PROFITS) RELATED TO THE SITE OR YOUR USE THEREOF REGARDLESS OF THE FORM OF ACTION WHETHER IN CONTRACT, TORT (INCLUDING NEGLIGENCE) OR OTHERWISE, EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES AND IN NO EVENT SHALL OUR MAXIMUM AGGREGATE LIABILITY EXCEED.
<br/>
YOU AGREE THAT NO CLAIMS OR ACTION ARISING OUT OF, OR RELATED TO, THE USE OF THE SITE OR THESE TERMS AND CONDITIONS MAY BE BROUGHT BY YOU MORE THAN ONE (1) YEAR AFTER THE CAUSE OF ACTION RELATING TO SUCH CLAIM OR ACTION AROSE. IF YOU HAVE A DISPUTE WITH US OR ARE DISSATISFIED WITH THE SITE, TERMINATION OF YOUR USE OF THE SITE IS YOUR SOLE REMEDY. WE HAVE NO OTHER OBLIGATION, LIABILITY, OR RESPONSIBILITY TO YOU.
<br/>
This disclaimer constitutes an essential part of this Terms of Use.

LINKS AND THIRD PARTY SITES
References on the Site to any names, marks, products or services of third parties or hypertext links to third party sites or information are provided solely as a convenience to you. This does not in any way constitute or imply Shopee Fashion endorsement, sponsorship or recommendation of the third party, information, product or service or any association and relationship between Shopee Fashion and those third parties.

Shopee Fashion is not responsible for the content of any third-party sites and does not make any representations regarding the content or accuracy of material on such sites. If you decide to link to any such third-party websites, you do so entirely at your own risk. Shopee Fashion do not assume any responsibility for examining or evaluating the offerings of the off-websites pages or any other websites linked from the Site. We shall not be responsible for the actions, content, products, or services of such pages and websites, including, without limitation, their privacy policies and terms and conditions. You should carefully review the terms and conditions and privacy policies of all off-website pages and other websites that you visit via the Site.

TERMINATION<br/>
These Terms of Use are effective unless and until terminated by either you or Shopee Fashion.
<br/>
You may terminate the Terms of Use at any time, provided that you discontinue any further use of this Site. Shopee Fashion may terminate the Terms of Use at any time and may do so without notice, and accordingly deny you access to the Site, such termination will be without any liability to the Site
<br/>
Upon any termination of the Terms of Use by either you or Shopee Fashion, you must promptly destroy all materials downloaded or otherwise obtained from this Site, as well as all copies of such materials, whether made under the Terms of Use or otherwise. Any such termination of the Terms of Use shall not cancel your obligation to pay for the product already ordered from the Site or affect any liability that may have arisen under the Terms of Use
<br/>
INDEMNITY<br/>
You agree to defend, indemnify and hold harmless Shopee Fashion, its employees, directors, officers, agents and their successors and assigns, its holding, subsidiaries, affiliates, partners, or licensors from and against any and all claims, liabilities, damages, losses, costs and expenses, including attorney's fees, caused by or arising out of claims based upon your actions or inactions, which may result in any loss or liability to Shopee Fashion or any third party including but not limited to breach of any warranties, representations or undertakings or in relation to the non-fulfilment of any of your obligations under the Terms of Use, or arising out of the your violation of any applicable laws, regulations including but not limited to Intellectual Property Rights, payment of statutory dues and taxes, claim of libel, defamation, violation of rights of privacy or publicity, loss of service by other subscribers and infringement of intellectual property or other rights. This clause shall survive the expiry or termination of the Terms of Use.
<br/>
GOVERNING LAW & JURISDICTION<br/>
The Terms of Use and the Policies shall be construed in accordance with the applicable laws of India. For proceedings arising therein the Courts at Mumbai shall have exclusive jurisdiction.
<br/>
Any dispute or difference either in interpretation or otherwise, of the Terms of Use and other Policies on the Site, between the parties hereto, shall be referred to an independent arbitrator who will be appointed by mutually and his decision shall be final and binding on the parties hereto. The above arbitration shall be in accordance with the Arbitration and Conciliation Act, 1996 as amended from time to time. The seat of arbitration shall be held in Mumbai.
<br/>
Without any prejudice to particulars listed in Clause 13 above, Shopee Fashion shall have the right to seek and obtain any injunctive, provisional or interim relief from any court of competent jurisdiction to protect its trade-mark or other intellectual property rights or confidential information or to preserve the status quo pending arbitration.

Shopee Fashion makes no representation that any products, services and materials displayed on the Site are appropriate or in compliance with laws for use in other locations/countries other than India. Those who choose to access this Site from other locations/countries other than India do so on their own initiative and Shopee Fashion shall not be responsible for supply of products/refund for the products ordered from other locations/countries other than India, compliance with local laws including custom duty, taxes, import regulations etc., if and to the extent local laws are applicable.

SITE SECURITY
You are prohibited from violating or attempting to violate the security of the Site, including, without limitation
<br/>
accessing data not intended for you or logging onto a server or an account which you are not authorized to access;
attempting to probe, scan or test the vulnerability of a system or network or to breach security or authentication measures without proper authorization;
attempting to interfere with service to any other user, host or network, including, without limitation, via means of submitting a virus to the Site, overloading, "flooding," "spamming," "mail bombing" or "crashing;"
sending unsolicited email, including promotions and/or advertising of products or services; or
forging any header or any part of the header information in any email or newsgroup posting. Violations of system or network security may result in civil or criminal liability.
Shopee Fashion is entitled to investigate occurrences that may involve such violations and may involve, and co-operate with, law enforcement authorities in prosecuting users who are involved in such violations. You agree not to use any device, software or routine to interfere or attempt to interfere with the proper working of this Site or any activity being conducted on this Site. You agree, further, not to use or attempt to use any engine, software, tool, agent or other device or mechanism (including without limitation browsers, spiders, robots, avatars or intelligent agents) to navigate or search this Site other than the search engine and search agents available from Shopee Fashion on this Site and other than generally available third-party web browsers (e.g., Netscape Navigator, Microsoft Explorer)
<br/>
GENERAL
If any part of these Terms of Use is determined to be invalid or unenforceable pursuant to applicable law including, but not limited to, the warranty disclaimers and liability limitations set forth above, then the invalid or unenforceable provision will be deemed to be superseded by a valid, enforceable provision that most closely matches the intent of the original provision and the remainder of the Terms of Use shall continue to be in effect. Unless otherwise specified herein, these Terms of Use constitutes the entire agreement between you and Shopee Fashion with respect to the Site/services and it supersedes all prior or contemporaneous communications and proposals, whether electronic, oral or written.
<br/>
Shopee Fashion’s failure to act with respect to a breach by you or others does not waive its right to act with respect to the breach or subsequent and similar breaches

You acknowledge and hereby agree to these Terms and Conditions and that it constitute the complete and exclusive agreement between us concerning your use of the Site, and supersede and govern all prior proposals, agreements, or other communications.
<br/>
We reserve the right, in our sole discretion, to change/ alter/ modify these Terms and Conditions at any time by posting the changes on the Site. Any changes are effective immediately upon posting to the Site. Your continued use of the Site thereafter constitutes your agreement to all such changed Terms and Conditions. We may, with or without prior notice, terminate any of the rights granted by these Terms and Conditions. You shall comply immediately with any termination or other notice, including, as applicable, by ceasing all use of the Site.
<br/>
Nothing contained in these Terms and Conditions shall be construed as creating any agency, partnership, or other form of joint enterprise between us. Our failure to require your performance of any provision hereof shall not affect our full right to require such performance at any time thereafter, nor shall our waiver of a breach of any provision hereof be taken or held to be a waiver of the provision itself. In the event that any provision of these Terms and Conditions shall be unenforceable or invalid under any applicable law or be so held by any applicable arbitral award or court decision, such unenforceability or invalidity shall not render these Terms and Conditions unenforceable or invalid as a whole but these Terms and Conditions shall be modified, to the extent possible, by the adjudicating entity to most fully reflect the original intent of the parties as reflected in the original provision. The headings in the Terms and Conditions are for convenience only and shall not be used in its interpretation.
<br/>
If you have any questions regarding these Terms and Conditions, support@Shopeefashion.com.
<br/>
CONTACT INFORMATION
<br/>
Please contact us for any questions or comments (including all inquiries unrelated to copyright infringement) regarding this website.
<br/>
Customer Service Desk
<br/>
E-mail id: <Link className="terms-link">support@shopeefashion.com</Link>
<br/>
Phone: 1800 266 3333
<br/>
Contact: Monday to Saturday, 10AM - 7PM
                    </p>
                </div>
            </div>
        </div>
    )
}
export default Terms;